/** The scheduler, mirrored from `agent/src/haze/scheduler/decide.py`.
 *
 *  This is the same algorithm the real agent runs, not an approximation of it.
 *  `web/tests/conformance.test.ts` replays a golden corpus generated by the
 *  Python test suite and fails if any decision differs — so the browser demo is
 *  provably running the real placement logic rather than something that merely
 *  looks like it.
 *
 *  If you change one implementation, the conformance test fails until you
 *  change the other. That is the point.
 *
 *  **Floating point**: Python and JavaScript both use IEEE 754 doubles, so the
 *  arithmetic agrees — but their rounding functions do not (Python's `round` is
 *  banker's rounding, JS `toFixed` rounds half away from zero). `roundTo4`
 *  below matches Python's `_round` exactly, and is the only rounding either
 *  side uses.
 */

export interface NodeCandidate {
  node_id: string;
  name: string;
  cores: number;
  ram_total: number;
  ram_available: number;
  cpu_percent: number;
  speed_factor: number;
  runtimes: string[];
  encoders: string[];
  has_gpu: boolean;
  gpu_name: string;
  latency_ms: number;
  throughput_mbps: number;
  is_self: boolean;
  simulated: boolean;
  online: boolean;
}

export interface JobRequirement {
  runtime: string;
  cpu_cores: number;
  ram_bytes: number;
  needs_gpu: boolean;
  preferred_encoders: string[];
  input_bytes: number;
  work_units: number;
}

export interface Assessment {
  node_id: string;
  name: string;
  eligible: boolean;
  score: number;
  dimensions: Record<string, number>;
  reasons: string[];
  estimated_seconds: number;
}

export interface Decision {
  chosen: string | null;
  summary: string;
  assessments: Assessment[];
}

const DEFAULT_THROUGHPUT_MBPS = 100.0;
const NEGLIGIBLE_INPUT_BYTES = 64 * 1024;

/** Matches Python's `_round`. Do not replace with `toFixed`. */
function roundTo4(value: number): number {
  if (!Number.isFinite(value)) return 0.0;
  return Math.floor(value * 10000 + 0.5) / 10000;
}

/** Formats a number for a reason string, identically to Python's `_fmt`.
 *
 *  Neither language's native decimal formatting is safe here: Python's
 *  `f"{v:.2f}"` rounds half to even and JS `toFixed` rounds half away from
 *  zero, so 0.125 renders as "0.12" in one and "0.13" in the other. The value
 *  is rounded with the same floor-based expression both agree on, then the
 *  string is assembled from integers, which are exact in both.
 */
function fmt(value: number): string {
  const negative = value < 0;
  const hundredths = Math.floor(Math.abs(value) * 100 + 0.5);
  const whole = Math.floor(hundredths / 100);
  const frac = hundredths % 100;

  let text: string;
  if (frac === 0) {
    text = String(whole);
  } else if (frac % 10 === 0) {
    text = `${whole}.${frac / 10}`;
  } else {
    text = `${whole}.${String(frac).padStart(2, '0')}`;
  }
  return negative && hundredths ? `-${text}` : text;
}

function transferSeconds(node: NodeCandidate, job: JobRequirement): number {
  if (node.is_self || job.input_bytes <= NEGLIGIBLE_INPUT_BYTES) return 0.0;
  const mbps = node.throughput_mbps > 0 ? node.throughput_mbps : DEFAULT_THROUGHPUT_MBPS;
  const bytesEachWay = job.input_bytes * 2;
  const seconds = (bytesEachWay * 8) / (mbps * 1_000_000);
  return seconds + (node.latency_ms * 2) / 1000.0;
}

function computeSeconds(node: NodeCandidate, job: JobRequirement): number {
  const speed = node.speed_factor > 0 ? node.speed_factor : 0.01;
  const contention = 1.0 + Math.min(100.0, Math.max(0.0, node.cpu_percent)) / 100.0;
  return (job.work_units / speed) * contention;
}

function ineligibility(node: NodeCandidate, job: JobRequirement): string | null {
  if (!node.online) return 'offline';
  if (!node.runtimes.includes(job.runtime)) return `does not have ${job.runtime}`;
  if (node.cores < job.cpu_cores) {
    return `has ${node.cores} cores, job needs ${job.cpu_cores}`;
  }
  if (node.ram_available < job.ram_bytes) {
    const need = Math.floor(job.ram_bytes / (1 << 20));
    const have = Math.floor(node.ram_available / (1 << 20));
    return `has ${have} MiB free, job needs ${need} MiB`;
  }
  if (job.needs_gpu && !node.has_gpu) return 'has no GPU';
  return null;
}

function affinity(node: NodeCandidate, job: JobRequirement): number {
  const wanted = job.preferred_encoders;
  if (wanted.length === 0) return !job.needs_gpu || node.has_gpu ? 1.0 : 0.0;
  const matched = wanted.filter((e) => node.encoders.includes(e));
  return roundTo4(matched.length / wanted.length);
}

function assess(
  node: NodeCandidate,
  job: JobRequirement,
  fastestCompute: number,
  fastestTotal: number,
): Assessment {
  const compute = computeSeconds(node, job);
  const transfer = transferSeconds(node, job);
  const total = compute + transfer;

  const score = total > 0 ? roundTo4(fastestTotal / total) : 1.0;

  const dimensions: Record<string, number> = {
    speed: compute > 0 ? roundTo4(fastestCompute / compute) : 1.0,
    headroom: roundTo4(1.0 - Math.min(100.0, Math.max(0.0, node.cpu_percent)) / 100.0),
    transfer: total > 0 ? roundTo4(compute / total) : 1.0,
    affinity: affinity(node, job),
  };

  const reasons: string[] = [];
  if (node.is_self) {
    reasons.push('runs here — nothing to transfer');
  } else if (transfer > 0.05) {
    const share = total > 0 ? Math.trunc(roundTo4((transfer / total) * 100)) : 0;
    reasons.push(
      `${fmt(transfer)}s moving ${Math.floor(job.input_bytes / 1024)} KiB each way ` +
        `(${share}% of the total)`,
    );
  }
  reasons.push(`~${fmt(compute)}s of compute at ${fmt(node.speed_factor)}×`);
  if (node.cpu_percent >= 70) {
    reasons.push(`busy — ${fmt(node.cpu_percent)}% CPU already`);
  }
  if (job.preferred_encoders.length > 0) {
    const matched = job.preferred_encoders.filter((e) => node.encoders.includes(e)).sort();
    reasons.push(matched.length > 0 ? `has ${matched.join(', ')}` : 'no preferred encoder');
  }
  if (job.needs_gpu && node.has_gpu && node.gpu_name) {
    reasons.push(`GPU: ${node.gpu_name}`);
  }

  return {
    node_id: node.node_id,
    name: node.name,
    eligible: true,
    score,
    dimensions,
    reasons,
    estimated_seconds: roundTo4(total),
  };
}

/** Best first, ineligible last, ties broken on node_id so the order is total. */
function ordered(assessments: Assessment[]): Assessment[] {
  return [...assessments].sort((a, b) => {
    if (a.eligible !== b.eligible) return a.eligible ? -1 : 1;
    if (a.score !== b.score) return b.score - a.score;
    return a.node_id < b.node_id ? -1 : a.node_id > b.node_id ? 1 : 0;
  });
}

export function decide(nodes: NodeCandidate[], job: JobRequirement): Decision {
  if (nodes.length === 0) {
    return { chosen: null, assessments: [], summary: 'no nodes available' };
  }

  const eligible: NodeCandidate[] = [];
  const assessments: Assessment[] = [];

  for (const node of nodes) {
    const reason = ineligibility(node, job);
    if (reason === null) {
      eligible.push(node);
    } else {
      assessments.push({
        node_id: node.node_id,
        name: node.name,
        eligible: false,
        score: 0.0,
        dimensions: {},
        reasons: [reason],
        estimated_seconds: 0.0,
      });
    }
  }

  if (eligible.length === 0) {
    return {
      chosen: null,
      assessments: ordered(assessments),
      summary:
        `no node can run ${job.runtime}: ` +
        assessments.map((a) => `${a.name} ${a.reasons[0]}`).join('; '),
    };
  }

  const fastestCompute = Math.min(...eligible.map((n) => computeSeconds(n, job)));
  const fastestTotal = Math.min(
    ...eligible.map((n) => computeSeconds(n, job) + transferSeconds(n, job)),
  );

  for (const node of eligible) {
    assessments.push(assess(node, job, fastestCompute, fastestTotal));
  }

  const ranked = ordered(assessments);
  const winner = ranked[0]!;
  const runnerUp = ranked.slice(1).find((a) => a.eligible);

  let summary: string;
  if (runnerUp === undefined) {
    summary = `${winner.name} was the only node that could run it`;
  } else {
    const margin = fmt(runnerUp.estimated_seconds - winner.estimated_seconds);
    const winnerComputesSlower =
      (winner.dimensions.speed ?? 1.0) < (runnerUp.dimensions.speed ?? 1.0);
    summary = winnerComputesSlower
      ? `${winner.name} — ${runnerUp.name} computes faster but is ${margin}s slower ` +
        `end to end once transfer is counted`
      : `${winner.name} — ${margin}s faster than ${runnerUp.name} end to end`;
  }

  return { chosen: winner.node_id, assessments: ranked, summary };
}
