import { ArrowUpRight } from 'lucide-react';

import { Eyebrow, Section } from '@/components/landing/Section';
import { InstallCommand } from '@/components/landing/InstallCommand';
import { Button } from '@/components/ui/Button';
import { navigate } from '@/lib/router';
import { REPO } from '@/lib/links';

/** Why this is worth trusting with a shell on your desktop.
 *
 *  Every claim here is checkable in the repository, which is the only kind
 *  this page is allowed to make: no logos, no user counts, no testimonials,
 *  no uptime figures. The fourth one is a link to the list of things Haze
 *  does *not* defend against, which is the part that makes the other three
 *  worth anything.
 */
const CLAIMS = [
  {
    title: 'Identity is a key, not an account',
    body: 'Every node is an Ed25519 keypair. Machines authenticate each other over TLS 1.3 with both ends pinned, and the client signs the server’s public key — which is what defeats a relay.',
  },
  {
    title: 'The demo runs the real scheduler',
    body: 'A golden corpus generated by the Python tests is replayed against the TypeScript in CI. Change one implementation and the build fails until you change the other.',
  },
  {
    title: 'Overhead is measured, not claimed',
    body: 'The benchmark script writes its results and its raw per-run data into the repository, including the runs where Haze loses. Roughly half a second, fixed.',
  },
  {
    title: 'And here is what it cannot do',
    body: 'Resource caps are not enforceable on macOS. Haze does not defend against a compromised paired machine. The threat model says so in full.',
    href: `${REPO}/blob/main/SECURITY.md`,
    linkLabel: 'Read the threat model',
  },
];

export function Trust() {
  return (
    <Section id="trust" className="border-t border-border-subtle">
      <Eyebrow>Security</Eyebrow>
      <h2 className="mt-3 max-w-xl text-balance text-2xl font-medium tracking-tight text-text-primary sm:text-3xl">
        It runs processes on your machines. That deserves specifics.
      </h2>

      <div className="mt-12 grid gap-x-8 gap-y-10 sm:grid-cols-2">
        {CLAIMS.map((claim) => (
          <div key={claim.title} className="border-t border-border pt-6">
            <h3 className="text-base font-medium text-text-primary">{claim.title}</h3>
            <p className="mt-2 max-w-md text-sm leading-relaxed text-text-secondary">
              {claim.body}
            </p>
            {claim.href && (
              <a
                href={claim.href}
                className="mt-3 inline-flex items-center gap-1 rounded text-sm text-accent-primary transition-colors ease-out-quart hover:text-accent-hover"
              >
                {claim.linkLabel}
                <ArrowUpRight size={14} strokeWidth={2} aria-hidden />
              </a>
            )}
          </div>
        ))}
      </div>
    </Section>
  );
}

/** The last thing before the footer. One action, stated plainly. */
export function FinalCta() {
  return (
    <Section className="border-t border-border-subtle bg-bg-secondary">
      <div className="mx-auto max-w-xl text-center">
        <h2 className="text-balance text-2xl font-medium tracking-tight text-text-primary sm:text-3xl">
          Try it before you install anything.
        </h2>
        <p className="mt-4 text-base leading-relaxed text-text-secondary">
          The simulated cluster runs entirely in this browser tab. Submit jobs, slow the network,
          take a machine offline mid-render — the hardware is fabricated, the scheduling is not.
        </p>
        <div className="mt-8 flex flex-wrap items-center justify-center gap-3">
          <Button variant="primary" size="xl" onClick={() => navigate('/cluster')}>
            Get started
          </Button>
          <InstallCommand size="xl" />
        </div>
      </div>
    </Section>
  );
}
