import { useMemo, useState } from 'react';

import { PROFILES } from '@/sim/profiles';
import { decide, type JobRequirement, type NodeCandidate } from '@/sim/scheduler';

/** The hero visual: the real scheduler, deciding.
 *
 *  This is not a picture of the product. `decide()` here is the same function
 *  the agent runs — the one a golden corpus generated by the Python test suite
 *  is replayed against in CI — so every number on screen, including the
 *  summary sentence, is computed rather than written.
 *
 *  The one control is the link between the machines, because that is the
 *  product's whole argument in a single click: on a LAN the 4×-faster machine
 *  wins by under a second, and one step down it loses outright. A page that
 *  only asserted "we account for transfer cost" would be making a claim; this
 *  lets the reader falsify it.
 */

const GiB = 1024 ** 3;
const MiB = 1024 ** 2;

/** Mirrors the demo cluster's `encode` job. */
const JOB: JobRequirement = {
  runtime: 'ffmpeg',
  cpu_cores: 2,
  ram_bytes: GiB,
  needs_gpu: false,
  preferred_encoders: ['hevc_nvenc'],
  input_bytes: 700 * MiB,
  work_units: 14,
};

const LINKS = [
  { id: 'lan', label: 'Fast LAN', multiplier: 1 },
  { id: 'wifi', label: 'Wi-Fi', multiplier: 6 },
  { id: 'slow', label: 'Slow link', multiplier: 20 },
] as const;

const SELF = 'laptop';

/** The demo cluster's three machines, held at their idle load so the panel is
 *  deterministic. Everything else is read from the same profiles the simulated
 *  cluster and `haze devnet` use. */
function candidates(multiplier: number): NodeCandidate[] {
  return PROFILES.map((profile) => {
    const isSelf = profile.name === SELF;
    return {
      node_id: profile.name,
      name: profile.name,
      cores: profile.cores,
      ram_total: profile.ramBytes,
      ram_available: Math.round(profile.ramBytes * 0.55),
      cpu_percent: profile.cpuMean,
      speed_factor: profile.speedFactor,
      runtimes: profile.gpu ? ['hashbench', 'blender', 'ffmpeg'] : ['hashbench', 'blender'],
      encoders: profile.gpu?.encoders ?? [],
      has_gpu: profile.gpu !== null,
      gpu_name: profile.gpu?.name ?? '',
      latency_ms: isSelf ? 0 : 3 * multiplier,
      throughput_mbps: isSelf ? 0 : 940 / multiplier,
      is_self: isSelf,
      simulated: true,
      online: true,
    };
  });
}

const HARDWARE = new Map(
  PROFILES.map((p) => [p.name, p.gpu ? `${p.cores} cores · ${p.gpu.name}` : `${p.cores} cores`]),
);

export function PlacementPreview() {
  const [link, setLink] = useState<(typeof LINKS)[number]['id']>('lan');
  const multiplier = LINKS.find((l) => l.id === link)?.multiplier ?? 1;
  const decision = useMemo(() => decide(candidates(multiplier), JOB), [multiplier]);

  return (
    <div className="overflow-hidden rounded-lg border border-border-subtle bg-bg-panel">
      <div className="flex flex-wrap items-center justify-between gap-x-3 gap-y-2 border-b border-border-subtle px-4 py-3">
        <div className="min-w-0">
          <h2 className="text-sm font-medium text-text-primary">Where should this run?</h2>
          <p className="mt-0.5 font-mono text-2xs text-text-muted">
            ffmpeg · 700 MiB in · prefers hevc_nvenc
          </p>
        </div>

        <div
          role="group"
          aria-label="Link between machines"
          className="flex shrink-0 gap-0.5 rounded-md border border-border-subtle bg-bg-tertiary p-0.5"
        >
          {LINKS.map((option) => (
            <button
              key={option.id}
              type="button"
              aria-pressed={link === option.id}
              onClick={() => setLink(option.id)}
              className={`rounded px-2 py-1 text-2xs transition-colors ease-out-quart ${
                link === option.id
                  ? 'bg-bg-elevated text-text-primary'
                  : 'text-text-muted hover:text-text-secondary'
              }`}
            >
              {option.label}
            </button>
          ))}
        </div>
      </div>

      <ul className="divide-y divide-border-subtle">
        {decision.assessments.map((a) => {
          const won = a.node_id === decision.chosen;
          return (
            <li key={a.node_id} className={`px-4 py-3 ${a.eligible ? '' : 'opacity-60'}`}>
              <div className="flex items-baseline justify-between gap-3">
                <span className="flex min-w-0 items-baseline gap-2">
                  <span
                    className={`min-w-0 truncate font-mono text-sm ${
                      won ? 'text-accent-primary' : 'text-text-primary'
                    }`}
                  >
                    {a.name}
                  </span>
                  <span className="min-w-0 truncate text-2xs text-text-dim">{HARDWARE.get(a.name)}</span>
                </span>
                <span
                  className={`shrink-0 font-mono text-xs tabular-nums ${
                    won ? 'text-accent-primary' : 'text-text-muted'
                  }`}
                >
                  {a.eligible ? `${a.estimated_seconds.toFixed(1)}s` : 'ineligible'}
                </span>
              </div>

              {a.eligible && (
                <div className="mt-2 h-1 overflow-hidden rounded-full bg-bg-tertiary">
                  <div
                    className={`h-full rounded-full transition-[width] duration-300 ease-out-quart ${
                      won ? 'bg-accent-primary' : 'bg-border-strong'
                    }`}
                    style={{ width: `${Math.max(2, a.score * 100)}%` }}
                  />
                </div>
              )}

              <p className="mt-2 text-2xs leading-relaxed text-text-muted">{a.reasons[0]}</p>
            </li>
          );
        })}
      </ul>

      <p
        aria-live="polite"
        className="border-t border-border-subtle bg-bg-tertiary/40 px-4 py-3 text-xs leading-relaxed text-text-secondary"
      >
        <span className="text-accent-primary">→ </span>
        {decision.summary}
      </p>
    </div>
  );
}
